### ISSUE TITLE
Change Newsletter section in Landing page

### ISSUE THREAD

**Issue by pedropcamellon** [dvstechlabs/Noteslify#102]
**Is your feature request related to a problem? Please describe.**
In section "Subscribe To Our Newsletter" appears a little vertical overflow showing scroll bars.

**Describe the solution you'd like**
Remove the overflow.

**Additional context**
![img](https://user-images.githubusercontent.com/83567517/194761641-9ceb36b8-2aa9-4834-a9b5-7a4156f26b62.png)

**Comment by devarshishimpi** [comment]
@Pcamellon Thanks For Pointing Out!! Do you want me to assign it to you as well?

**Comment by Pcamellon** [comment]
Yes! Thanks

**Comment by Pcamellon** [comment]
In NewsLetter component I converted the Function to a Class and tried accessing the elements inside of iframe like this but I'm getting null:

```
class NewsLetter extends React.Component {
  constructor(props) {
    super(props);
    this.iframe = React.createRef();
  }

  componentDidMount() {
    // This returns null
    console.log(
      this.iframe.current.contentWindow.document.querySelector(
        ".sharedForm"
      )
    );
  }

  render() {
    return (
      <section className="news-section">
        <iframe
          title="newsletter"
          src="https://airtable.com/embed/shrUwGnyLnDvLvBoJ?backgroundColor=purple"
          width="100%"
          height="100%"
          frameBorder="0"
          allowFullScreen=""
          style={{
            position: "absolute",
            top: "0",
            left: "0",
          }}
          ref={this.iframe}
        ></iframe>
      </section>
    );
  }
}

export default NewsLetter;
```

**Comment by devarshishimpi** [comment]
> In NewsLetter component I converted the Function to a Class and tried accessing the elements inside of iframe like this but I'm getting null:
> 
> ```
> class NewsLetter extends React.Component {
>   constructor(props) {
>     super(props);
>     this.iframe = React.createRef();
>   }
> 
>   componentDidMount() {
>     // This returns null
>     console.log(
>       this.iframe.current.contentWindow.document.querySelector(
>         ".sharedForm"
>       )
>     );
>   }
> 
>   render() {
>     return (
>       <section className="news-section">
>         <iframe
>           title="newsletter"
>           src="https://airtable.com/embed/shrUwGnyLnDvLvBoJ?backgroundColor=purple"
>           width="100%"
>           height="100%"
>           frameBorder="0"
>           allowFullScreen=""
>           style={{
>             position: "absolute",
>             top: "0",
>             left: "0",
>           }}
>           ref={this.iframe}
>         ></iframe>
>       </section>
>     );
>   }
> }
> 
> export default NewsLetter;
> ```
> 
> This is the element I'm traying to acces for removing the overflow:
> 
> ![Subscribe To Our Newsletter 2](https://user-images.githubusercontent.com/83567517/194769222-19d1d30c-08d4-49cd-aa76-ae4fc8701f69.png)
> 
> They say "You can't access the contents of an iFrame if it's cross-domain. See [Same-Origin policy](http://en.wikipedia.org/wiki/Same-origin_policy)." [here](https://stackoverflow.com/questions/926916/how-to-get-the-bodys-content-of-an-iframe-in-javascript).
> 
> Do we need to use the embedded option or could we try making our own form and posting and fetching trough airtable api ?

We'll probably shift to our own form with Airtable API. I think we'll go with formspree

**Comment by devarshishimpi** [comment]
You can work on a custom form and add it to that section. We'll use formspree for submitting the forms and then Zapier to integrate with Airtable, or maybe Formspree's direct integration with Airtable

**Comment by Pcamellon** [comment]
Here is a prototype I made in [Figma](https://www.figma.com/file/LG9p22NDsO9iSZ5KPyIWgf/Untitled?node-id=101%3A4).

**Comment by khushi818** [comment]
It looks amazing. What if we centralize the heading for desktop version?

**Comment by devarshishimpi** [comment]
Yep, Works

**Comment by devarshishimpi** [comment]
> It looks amazing. What if we centralize the heading for desktop version?

Hmm, and then later responsive in the center for mobile devices as well

**Comment by Pcamellon** [comment]
***Desktop*** *(three variations, now with the right proportions)*
1. 
![image](https://user-images.githubusercontent.com/83567517/194884115-87beb577-062f-4bda-97b7-2d874574e4c2.png)

2. 
![image](https://user-images.githubusercontent.com/83567517/194890618-624fd93e-1b96-4f81-b1d7-debb4c766291.png)

3.
![image](https://user-images.githubusercontent.com/83567517/194890778-fc3747db-d7e7-4822-857c-135bf09b5d51.png)

***Mobile*** *(two variations)*
1.
![image](https://user-images.githubusercontent.com/83567517/194890304-535a2d85-246a-4107-9dfc-25b37bc09e15.png)

2.
![image](https://user-images.githubusercontent.com/83567517/194890344-1e44d525-884a-45a5-a39d-e017aa218c2f.png)

**Comment by pedropcamellon** [comment]
I'm on it!

**Comment by pedropcamellon** [comment]
Sharing my progress:

![image](https://user-images.githubusercontent.com/83567517/194934685-3ac57556-3393-4084-80dc-ec7f62f769a0.png)

I'm having trouble with getting that checkmark done :(

**Comment by pedropcamellon** [comment]
Done!
![image](https://user-images.githubusercontent.com/83567517/194951097-3bc6de64-f3ad-4563-9048-492306df40ed.png)

**Comment by devarshishimpi** [comment]
Is the background matching and looking good with the rest website content? Like the footer and the about section above it?

**Comment by pedropcamellon** [comment]
I think it is. I have to remove a margin at the top of the footer section.

*Mobile*
![image](https://user-images.githubusercontent.com/83567517/195180105-d668b0e9-5fb4-4f11-bcba-837a1bb387d7.png)

*Desktop*
![image](https://user-images.githubusercontent.com/83567517/195180213-8c9a9b60-cba0-4bb5-9f5a-e5025cfb81de.png)

**Comment by pedropcamellon** [comment]
Form will do nothing:
`<form action="" class="newsletter__form text-center">`

**Comment by devarshishimpi** [comment]
Looks great @pedropcamellon Could you update with the latest branch, since the footer has been changed, and it would need a white background?

**Comment by devarshishimpi** [comment]
> Form will do nothing: `<form action="" class="newsletter__form text-center">`

That's fine, I'll add that later on.

**Comment by pedropcamellon** [comment]
Can you guide me with that? I'll fork the project. Work on my fork in pedropcamellon/noteslify. What do I do after?

**Comment by devarshishimpi** [comment]
I can't find the branch for the same. Probably, write the code with the new footer at the bottom.
I have to change few settings in the footer as well, but I'll keep it as it is for now until your PR has been made.

**Comment by devarshishimpi** [comment]
> That's the thing. I dont know how to send my changes.

I can't find your branch. Could you make a new branch in your fork and then commit all of them there? Or even works from your main branch of the fork.

**Comment by pedropcamellon** [comment]
I couldn't commit because the branch appeared as protected. That was what I mentioned before. It get fixed, i dont know how. I made the commits, push changes and pull request.

**Comment by devarshishimpi** [comment]
Good that's fixed.

**Comment by pedropcamellon** [comment]
Can you please check what I did above? I dont have much xp with Github.

- I forked the project and worked on my copy in pedropcamellon/noteslify. I'm seeing this:
![image](https://user-images.githubusercontent.com/83567517/195366434-589181d4-a4f7-4c5d-8e1b-47ec981c8f8a.png)

- I made some commits:
![image](https://user-images.githubusercontent.com/83567517/195366989-6012cdf5-22e7-4608-8017-5e249b10fa59.png)

**Comment by devarshishimpi** [comment]
Yes, all of those commits are perfect. Simply go back to your Github Code which you wrote. And then add your code back there. It seems like pulling from the main branch removed your code. Simply copy paste the code from your commits back into the repository code and check if everything is working fine. If yes, commit it to your fork. It will get updated here automatically.

**Comment by MrKrishnaAgarwal** [comment]
This issue was completed in #136 

Closing!!

**Comment by devarshishimpi** [comment]
Wasn't yet completed

**Comment by MrKrishnaAgarwal** [comment]
Okay!
