### ISSUE TITLE
Add animation in the navbar

### ISSUE THREAD

**Issue by CoderAayush2104** [dvstechlabs/Noteslify#103]
Please assign it to me.I will do it for you

**Comment by devarshishimpi** [comment]
Actually, this has been added and just updated in production

**Comment by devarshishimpi** [comment]
You may want to work on this https://github.com/dvstechlabs/Noteslify/issues/104

**Comment by devarshishimpi** [comment]
Or this https://github.com/dvstechlabs/Noteslify/issues/105
