### ISSUE TITLE
Add a better footer section  to Landing Page ( Responsive )

### ISSUE THREAD

**Issue by devarshishimpi** [dvstechlabs/Noteslify#104]

**Comment by ron-huberfeld** [comment]
Hi @devarshishimpi 
Can I have this?

**Comment by bhumika-1-3** [comment]
Can I make a better footer for the page?

**Comment by devarshishimpi** [comment]
Sure, I have assign you both

**Comment by ron-huberfeld** [comment]
@devarshishimpi, can you please comment about the existing footer - what is wrong with it?
![image](https://user-images.githubusercontent.com/32178925/194884616-2ec280b2-c6a8-48f5-b1f8-ebcd6cc31f4c.png)

**Comment by devarshishimpi** [comment]
@ron-huberfeld 

It's a google picture, but similar to this, while being responsive
![image](https://user-images.githubusercontent.com/43378923/194886437-1057f1bf-0383-4089-b7d9-b158ebde2376.png)

**Comment by bhumika-1-3** [comment]
I will do it.

**Comment by devarshishimpi** [comment]
> I will do it.

Sure, Have assigned you already.

**Comment by bhumika-1-3** [comment]
![image](https://user-images.githubusercontent.com/80103105/194890272-533c7803-8f7d-4a1f-bd09-bc80c59179b2.png)

Will this format be fine ?

**Comment by bhumika-1-3** [comment]
![image](https://user-images.githubusercontent.com/80103105/194895308-c2b56e6f-42a7-4522-9c59-9c60bb15e498.png)

how is this

**Comment by devarshishimpi** [comment]
> ![image](https://user-images.githubusercontent.com/80103105/194895308-c2b56e6f-42a7-4522-9c59-9c60bb15e498.png)
> 
> how is this

Works, I hope it's responsive as well.

**Comment by bhumika-1-3** [comment]
yes it is
![image](https://user-images.githubusercontent.com/80103105/194898734-5df667cc-8266-424d-bc3b-30e57dc25a1b.png)

**Comment by devarshishimpi** [comment]
Great!

**Comment by devarshishimpi** [comment]
Fixed
