### ISSUE TITLE
Notes Page Goes Blank after login and needs a page refresh

### ISSUE THREAD

**Issue by devarshishimpi** [dvstechlabs/Noteslify#108]
![image](https://user-images.githubusercontent.com/43378923/194806940-e838907a-7ab0-4ec9-bfc6-03a7c67a35a9.png)

Notes page goes blank after login and needs a page refresh in order to view the notes

**Comment by IncredibleZuess** [comment]
Hey @devarshishimpi! Can I work on this one?

**Comment by devarshishimpi** [comment]
Sure
