### ISSUE TITLE
Add Zero Knowledge Encryption

### ISSUE THREAD

**Issue by devarshishimpi** [dvstechlabs/Noteslify#110]
Encrypt Notes before saving them to MongoDB, and the same while retrieving it

**Comment by Gauravdarkslayer** [comment]
Hey @devarshishimpi , I would like to work on this issue. Can you please assign it to me ? 
Thanks !!

**Comment by devarshishimpi** [comment]
Hi, Sure

**Comment by Gauravdarkslayer** [comment]
Hi @devarshishimpi , Do we have to encrypt title and description both?

**Comment by devarshishimpi** [comment]
Fixed

**Comment by devarshishimpi** [comment]
Also @Gauravdarkslayer Do check my email sent to you
