### ISSUE TITLE
Introducing a Back to Top Button ↑

### ISSUE THREAD

**Issue by Vineet-0** [dvstechlabs/Noteslify#111]
**Is your feature request related to a problem? Please describe.**
As I go through your site several times and face an issue that there is no button Back to Top so I have to scroll it 
so here is  my solution for this, I am introducing a Back to Top

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by devarshishimpi** [comment]
Great Idea!

**Comment by williamssam** [comment]
@devarshishimpi is this still up for grabs??

**Comment by devarshishimpi** [comment]
> @devarshishimpi is this still up for grabs??

Yes

**Comment by williamssam** [comment]
> > @devarshishimpi is this still up for grabs??
> 
> 
> 
> Yes

Thanks ☺️
