### ISSUE TITLE
Adding placeholder in add note popup

### ISSUE THREAD

**Issue by biswajit035** [dvstechlabs/Noteslify#112]
**ADDING PLACEHOLDER TO ADD NOTE POPUP**

I would like to add a placeholder to the add note popup which will increse the user experience and will look more functional.

**BEFORE CHANGE**
![BEFORE](https://user-images.githubusercontent.com/88304589/194823498-74bad327-8234-41c1-a214-39dbaca765b6.jpg)

**AFTER CHANGE**
![AFTER](https://user-images.githubusercontent.com/88304589/194823530-131e642c-1085-4ade-a6c0-649cc8a498dc.jpg)

**Comment by biswajit035** [comment]
PLEASE ASSIGN ME FOR THIS TASK

**Comment by devarshishimpi** [comment]
Yes sure.

**Comment by devarshishimpi** [comment]
Fixed
