### ISSUE TITLE
State is maintained after preview window is closed and add new note modal is open

### ISSUE THREAD

**Issue by Ravina-Deogadkar** [dvstechlabs/Noteslify#116]
**Describe the bug**
The state is not getting cleared after we close the preview and open Add new note modal.

**To Reproduce**
1. Create a new note
2. Click on the newly created note, and the preview window will open.
3. Close the preview window.
4. Click on Add new note.

**Expected behavior**
Add new note should have blank textbox everytime.

**Screenshots**
![noteslify-bug](https://user-images.githubusercontent.com/49125074/194849934-60fed52e-c76a-4807-a9e6-d7fbc40142be.png)

**Comment by devarshishimpi** [comment]
Yes, Thanks For Pointing that out.

**Comment by nirajpdn** [comment]
I want to do this

**Comment by devarshishimpi** [comment]
> I want to do this

Sure

**Comment by devarshishimpi** [comment]
Both PRs got merged. Will have to check with the same.
