### ISSUE TITLE
Markdown editor not showing up in production

### ISSUE THREAD

**Issue by devarshishimpi** [dvstechlabs/Noteslify#117]
![image](https://user-images.githubusercontent.com/43378923/194852455-addf97f1-7b71-4166-9ba9-d5f0055a3de0.png)

Here's the preview of the output of the markdown editor

**Comment by Ravina-Deogadkar** [comment]
Let me check this

**Comment by nmathew98** [comment]
@devarshishimpi can I be assigned to this?

**Comment by devarshishimpi** [comment]
Yes sure.

**Comment by devarshishimpi** [comment]
Fixxed
