### ISSUE TITLE
🐛 [BUG] -  The first-time login shows a blank page.

### ISSUE THREAD

**Issue by ann0nip** [dvstechlabs/Noteslify#128]
### Description

The issue is due to a request API error. But if you refresh the page, all works fine.

I want to debug and see if I can fix itSo pleasese sign this issue to me.

<img width="973" alt="Screen Shot 2022-10-11 at 10 14 10" src="https://user-images.githubusercontent.com/2248100/195105009-9bed66f5-e838-4930-bd1d-b1ed2d6081c5.png">

### Reproduction URL

http://localhost:3001/notes

### Reproduction steps

```bash
1. Go to 'https://noteslify.stonecss.com/login'
2. Enter your username and password
3. The first time the page load, it shows an empty page.
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome, Safari

### OS

Mac

**Comment by devarshishimpi** [comment]
@ann0nip Thanks For Pointing out the issue as well as the fix!! 🙌🏻
