### ISSUE TITLE
 Button to Top

### ISSUE THREAD

**Issue by chintan0513** [dvstechlabs/Noteslify#129]
### Start Date

10/11/2022

### Summary

I will add a button on the left side which redirects the user to the top from the bottom.

### Basic Example

This is the basic example that I mentioned in summary

### Drawbacks

It mainly reduces the space in the portal, for example, 5 to 20px right side.

**Comment by devarshishimpi** [comment]
@chintan0513 Hey, this was already added in https://github.com/dvstechlabs/Noteslify/pull/124
