### ISSUE TITLE
Add a cursor pointer property to footer social link buttons🐛 [BUG] - <title>

### ISSUE THREAD

**Issue by anshulsoni4** [dvstechlabs/Noteslify#135]
### Description

I think there is no cursor pointer added to the buttons present in the footer section. I would like to add that feature.

### Reproduction URL

https://github.com/dvstechlabs/Noteslify/issues

### Reproduction steps

```bash
1. Go to 'footer'
2. hover to 'social buttons'
4. See the error
```

**Comment by THEYASHGAUR** [comment]
Hey 
I know how to solve this, can you please assign this issue to me.

**Comment by THEYASHGAUR** [comment]
Hey
**I know how to solve this problem, can you please assign this issue to me.**

**Comment by devarshishimpi** [comment]
Sure

**Comment by devarshishimpi** [comment]
@THEYASHGAUR @anshulsoni4 Can we complete it within next 2 days?

**Comment by whizzbbig** [comment]
> @THEYASHGAUR @anshulsoni4 Can we complete it within next 2 days?

Hi can you assign me so not only i can change the way those social icons work but also manage the whole footer the way you want

**Comment by THEYASHGAUR** [comment]
ok we will work in this issue together

**Comment by anshulsoni4** [comment]
> ok we will work in this issue together

sure thing

**Comment by whizzbbig** [comment]
@devarshishimpi resolved the issue please check #142

**Comment by whizzbbig** [comment]
don't forget to assign me tho

**Comment by devarshishimpi** [comment]
Fixed
