### ISSUE TITLE
adding active class to SIDENAV 

### ISSUE THREAD

**Issue by biswajit035** [dvstechlabs/Noteslify#138]
I want to add  **ACTIVE** class according to url so that we can have a idea about our current tav in **SIDENAV**.
I added **#e4e9f7** color as background of active class so the active tab's background will be highlighted with this color.

BEFORE
![BEFORE](https://user-images.githubusercontent.com/88304589/195557430-2dce5e6c-26c8-48d9-96f5-eb0e81ba82d6.jpg)

AFTER
![AFTER](https://user-images.githubusercontent.com/88304589/195557505-deb83d44-be2d-45fb-a382-cca23f156dd7.jpg)

**Comment by biswajit035** [comment]
I would like to work on it. Can you please assign it to me.

**Comment by devarshishimpi** [comment]
Great!! Yes sure.

**Comment by devarshishimpi** [comment]
Fixed
