### ISSUE TITLE
🐛 [BUG] - Floating button overlaying footer content

### ISSUE THREAD

**Issue by BrunoLagoa** [dvstechlabs/Noteslify#144]
### Description

Floating button overlaying footer content.

### Reproduction URL

https://noteslify.stonecss.com

### Reproduction steps

```bash
1. Go to home
2. Scroll down to footer page
3. See error
```

### Screenshots

```bash
![Captura de Tela 2022-10-14 às 09 58 13](https://user-images.githubusercontent.com/3878945/195853524-39f47eee-de07-4d26-9dcd-2752e0dbaf3c.png)
```

### Browsers

Chrome

### OS

Mac

**Comment by whizzbbig** [comment]
@devarshishimpi To resolve this i think footer can be redesign, what you think? if you agree with it i'll come with a new design and implement it in no time

**Comment by devarshishimpi** [comment]
The older footer was just basic, even this one is quite basic and needs upgrade ( similar design ), So yes.

**Comment by BrunoLagoa** [comment]
A small adjustment in the footer, for me it would solve it. 

![Uploading Captura de Tela 2022-10-14 às 14.18.10.png…]()

**Comment by devarshishimpi** [comment]
Works!! You may customize the footer a bit as well, making it better.

**Comment by BrunoLagoa** [comment]
I was wondering, can I work on this adjustment or is there already someone working? =)

**Comment by whizzbbig** [comment]
![Screenshot 2565-10-15 at 12 22 09 AM](https://user-images.githubusercontent.com/54703305/195919973-71394246-192c-45d2-a3fe-fdf757014353.png)
@devarshishimpi  this is the design i came up with just now made it quickly sorry for responding late so the thing here we gonna change is 

to give the space to the content in the footer so they can breathe
and change some positioning to make them consistent and aligned properly

rest things gonna be the same

**Comment by devarshishimpi** [comment]
looks good, this works

**Comment by whizzbbig** [comment]
> looks good, this works

am gonna implement it now will push in mins till then if you have anything to implement you can count me in also i have some designs in mind for our hero will keep you posted

https://user-images.githubusercontent.com/54703305/195979178-96fcb36c-bbba-4a27-8497-0f1c30962e46.mov

**Comment by devarshishimpi** [comment]
Okay 👍🏻

**Comment by whizzbbig** [comment]
@devarshishimpi  done 👍🏻

**Comment by whizzbbig** [comment]
@devarshishimpi i also made it responsive :)

**Comment by devarshishimpi** [comment]
Reviewed, Requires few changes

**Comment by whizzbbig** [comment]
> Reviewed, Requires few changes

yes state them

**Comment by devarshishimpi** [comment]
> > Reviewed, Requires few changes
> 
> yes state them

have added them in the PR itself

**Comment by devarshishimpi** [comment]
Fixed
