### ISSUE TITLE
Other Dark mode for the website

### ISSUE THREAD

**Issue by krishnabiradar310802** [dvstechlabs/Noteslify#148]
### What would you like to share?

Now a days people are using dark mode so i can add it to the website

**Comment by devarshishimpi** [comment]
Hi There, Thanks. The same issue is in https://github.com/dvstechlabs/Noteslify/issues/3. Could you comment there so that I can assign you?

**Comment by devarshishimpi** [comment]
Here. Linked the wrong one https://github.com/dvstechlabs/Noteslify/issues/37
