### ISSUE TITLE
Github link on header is redirecting to old repo(archived Repo) 

### ISSUE THREAD

**Issue by PrakashGatiyala** [dvstechlabs/Noteslify#151]
### What would you like to share?

![image](https://user-images.githubusercontent.com/34413515/196023727-e0100bdf-017c-46bb-b259-98a33fea26d7.png)

Above github link is redirecting to archived repo.

![image](https://user-images.githubusercontent.com/34413515/196023742-77245ace-cf7c-47b5-a4f3-39373b55f842.png)

I want to fix this link. 
Hi @devarshishimpi  Can you assign me this issue?

**Comment by devarshishimpi** [comment]
Yes sure

**Comment by devarshishimpi** [comment]
There may be another at the bottom

**Comment by PrakashGatiyala** [comment]
> There may be another at the bottom

Footer one was already correct.

**Comment by PrakashGatiyala** [comment]
Hi @devarshishimpi I've created the PR for it. PR link: https://github.com/dvstechlabs/Noteslify/pull/152
Please review it and merge it.

**Comment by devarshishimpi** [comment]
Merged
