### ISSUE TITLE
git links in package.json is referring to old(archived) repo. 

### ISSUE THREAD

**Issue by PrakashGatiyala** [dvstechlabs/Noteslify#156]
### What would you like to share?

![image](https://user-images.githubusercontent.com/34413515/196039771-81cfa1a3-ac12-492f-b4e9-9ead00f4abd9.png)

Hi, as you can see in above image, git links in package.json is referring to old(archived) repo.  
same issue is for Front-end [package.json](https://github.com/dvstechlabs/Noteslify/blob/main/frontend/package.json) and backend [package.json](https://github.com/dvstechlabs/Noteslify/blob/main/backend/package.json)

I want to update these links with current repo links. 

Hi @devarshishimpi  Can you assign me this issue ?

**Comment by devarshishimpi** [comment]
Yes sure

**Comment by devarshishimpi** [comment]
Could you update the description as well to the current one?

**Comment by PrakashGatiyala** [comment]
> Could you update the description as well to the current one?

Should I replace description with _**Your Privacy Friendly, Open Source. Alternative to EverNote.**_  ?

**Comment by devarshishimpi** [comment]
Merged
