### ISSUE TITLE
💡 [REQUEST] - Make contribution.md clickable on README file to navigate to the contribution page dynamically.

### ISSUE THREAD

**Issue by RakibRahman** [dvstechlabs/Noteslify#165]
### Implementation PR

#164

### Summary

As of now, we have to manually navigate to the contribution and code_of_conduct page if we want to check it out. It would be a better user experience if the user can directly visit the contribution and code_of_conduct page by clicking from the REAME.md file.

### Basic Example

None

### Drawbacks

None

**Comment by RakibRahman** [comment]
completed all the steps and raised an issue.

**Comment by devarshishimpi** [comment]
> completed all the steps and raised an issue.

Merged
