### ISSUE TITLE
Fixing dashboard background

### ISSUE THREAD

**Issue by biswajit035** [dvstechlabs/Noteslify#167]
When there are few numbers of note and you have to scroll down to acces them then you can saw there is no background color in **DASHBOARD** page.
![image](https://user-images.githubusercontent.com/88304589/196227646-5c3499f6-1fe1-4d56-838b-92ddb90de866.png)

**Comment by biswajit035** [comment]
I want to work on it. Can you please assign it to me?

**Comment by devarshishimpi** [comment]
Yes sure

**Comment by devarshishimpi** [comment]
Fixed
