### ISSUE TITLE
🐛 [BUG] - The Navigation of Mobile Orientation looks Odd and Quirky 

### ISSUE THREAD

**Issue by whizzbbig** [dvstechlabs/Noteslify#168]
### Description

https://user-images.githubusercontent.com/54703305/196265441-666efabc-e087-4e41-80ad-cbecdb2cb592.mov

the navigation of mobile orientation looks odd and quirky because of its transition the way it comes too quickly gives the feeling of hesitation things are too small like logo and hamburger. menu should have their own space 

### Reproduction URL

https://noteslify.stonecss.com/

### Reproduction steps

```bash
1. Go to link mentioned in reproduction url
2. Go to portrait orientation to see the behaviour of navigation
3. You'll notice how small and quirky it is
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Mac

**Comment by MrKrishnaAgarwal** [comment]
_Tagging @devarshishimpi If it's a bug which is needed to be resolved._

**Comment by devarshishimpi** [comment]
@whizzbbig I have assigned you to it

**Comment by whizzbbig** [comment]
I give up on this there is lot of things going on css like way lot of css realted to buttons its like a loophole no matter wherever i try to fix it it just append to yet another styles related to it and it literally gives me spine chills with the js part :'c

**Comment by devarshishimpi** [comment]
> I give up on this there is lot of things going on css like way lot of css related to buttons its like a loophole no matter wherever i try to fix it it just append to yet another styles related to it and it literally gives me spine chills with the js part :'c

I think the CSS files really need lots of refactoring. The last time it was done was like 15-20 days ago. Since then, maybe new PRs and commits are overlapping over each other

**Comment by EmmanuelAllanMJ** [comment]
Can I work on this issue

## Expected outcome

![nav design](https://user-images.githubusercontent.com/90669430/197977894-da44ed5b-2c01-45a0-8f79-dfffcb1c3478.gif)

**Comment by devarshishimpi** [comment]
Sure

**Comment by devarshishimpi** [comment]
Fixed
