### ISSUE TITLE
🐛 [BUG] - Mockups Contain White square background 

### ISSUE THREAD

**Issue by whizzbbig** [dvstechlabs/Noteslify#176]
### Description

Mockups in Noteslify sections Contain White square background which represents bad UX

### Reproduction URL

https://noteslify.stonecss.com/

### Reproduction steps

```bash
1. Go to link given above
2. Scroll down to sections and you'll notice that
```

### Screenshots

https://user-images.githubusercontent.com/54703305/196759477-f409b058-5dda-4846-98b5-c768e89e00b6.mov

### Browsers

Chrome

### OS

Mac

**Comment by whizzbbig** [comment]
@devarshishimpi can you add hactoberfest tags in this issue

**Comment by devarshishimpi** [comment]
Fixed
