### ISSUE TITLE
Change position of EDIT and DELETE note button

### ISSUE THREAD

**Issue by biswajit035** [dvstechlabs/Noteslify#178]
Place the EDIT and DELETE button on the buttom of every note.

ADVANTAGES:
  Before we need to click 2 times to edit / delete a notes.
  But now we can do the same job by one simple click only. 

**BEFORE**
![image](https://user-images.githubusercontent.com/88304589/196966682-70fb4092-a3c3-44f7-8d60-48d2267a0640.png)

**AFTER**
![image](https://user-images.githubusercontent.com/88304589/196966735-a7629775-d452-4f6c-9cf1-c31b5a4e1aac.png)

**Comment by biswajit035** [comment]
Is it acceptable to do that changes?

**Comment by deepaksuthar40128** [comment]
can you assign it to me?

**Comment by devarshishimpi** [comment]
> Is it acceptable to do that changes?

Yes, just have some gap between those buttons tho

**Comment by devarshishimpi** [comment]
> can you assign it to me?

Sure

**Comment by devarshishimpi** [comment]
Fixed
