### ISSUE TITLE
On mouse hover, social media Icon should show App-Name

### ISSUE THREAD

**Issue by PrakashGatiyala** [dvstechlabs/Noteslify#182]
### What would you like to share?

![image](https://user-images.githubusercontent.com/34413515/197344854-14102822-b699-43d8-96f4-0209062abedd.png)

At Footer section, I have found out that while mouse hovering over social media Icon, I can't see social media Name. 

On mouse hovering, it should show like this:
![image](https://user-images.githubusercontent.com/34413515/197345180-eb251e40-808e-47ba-a3ed-cb21ff79a935.png)

Hi @devarshishimpi  I want to work on this issue. Can you assign it to me?

**Comment by Gauravdarkslayer** [comment]
Hey @PrakashGatiyala , I assigned this issue to you, go ahead. :)

**Comment by PrakashGatiyala** [comment]
> Hey @PrakashGatiyala , I assigned this issue to you, go ahead. :)

Hi @Gauravdarkslayer I've created Pr for it. PR link: https://github.com/dvstechlabs/Noteslify/pull/183

Please review it and merge it

**Comment by devarshishimpi** [comment]
Fixed
