### ISSUE TITLE
💡 Password field don't have length limit

### ISSUE THREAD

**Issue by Rimjhim20** [dvstechlabs/Noteslify#187]
## Password validation.
Password numbers should have limit. 
Ideally, Passwords should be 6 to 24 in length.
I want to add validation for it.
Hi, @devarshishimpi Assign me with this issue.

**Comment by devarshishimpi** [comment]
Okay sure

**Comment by Rimjhim20** [comment]
> Okay sure

Hi @devarshishimpi , I have created PR for it. PR link: https://github.com/dvstechlabs/Noteslify/pull/193
Kindly review it and merge it.

**Comment by devarshishimpi** [comment]
Done
