### ISSUE TITLE
SignUp/Signin UI modification 

### ISSUE THREAD

**Issue by Rimjhim20** [dvstechlabs/Noteslify#189]
### What would you like to share?

Hii! @devarshishimpi  I go through the Noteslify website and found some CSS issues while inputting email, pass , username...
I fixed that CSS issue and created PR for this.
Thanks
![1](https://user-images.githubusercontent.com/71636845/197920201-1570a529-d021-43de-8eda-7192c40471c0.png)

**Comment by devarshishimpi** [comment]
Okay sure

**Comment by PrakashGatiyala** [comment]
> Okay sure

Hi @devarshishimpi I have created a PR for this. PR link: https://github.com/dvstechlabs/Noteslify/pull/191
Please review it and merge it

**Comment by Rimjhim20** [comment]
> Okay sure

Hi @devarshishimpi  I have created a PR for it. PR link: https://github.com/dvstechlabs/Noteslify/pull/191

Please review it and merge it.

**Comment by devarshishimpi** [comment]
Merged
