### ISSUE TITLE
Other <Code clean-up remove unused Variables>

### ISSUE THREAD

**Issue by PrakashGatiyala** [dvstechlabs/Noteslify#194]
### What would you like to share?

![image](https://user-images.githubusercontent.com/34413515/198060605-a3f90984-90b0-4005-a0af-0e4eed3e9979.png)

As you can see, while running this application,  There are few warning related to **no-unused-vars**. 
I want to clean these warning by deleting the unused variables.  

Hi @devarshishimpi  I want to work on this issue. Please assign it to me.

**Comment by devarshishimpi** [comment]
@PrakashGatiyala Those warnings are to be filled up in the future. No plans on removing them since we'll need the required vars
