### ISSUE TITLE
Username field don't have length limit. 

### ISSUE THREAD

**Issue by PrakashGatiyala** [dvstechlabs/Noteslify#195]
### What would you like to share?

![image](https://user-images.githubusercontent.com/34413515/198087163-9ca66645-29d9-4885-ad4c-82aacaee3d58.png)

Username should have length limit.  Username should be 6–30 characters long.
I want to add this validation for it.
Hi, @devarshishimpi I want to work on this issue. Please assign it to me.

**Comment by MrKrishnaAgarwal** [comment]
@devarshishimpi do we need it?

**Comment by devarshishimpi** [comment]
> @devarshishimpi do we need it?

Yep

**Comment by PrakashGatiyala** [comment]
> > @devarshishimpi do we need it?
> 
> Yep

Hi @devarshishimpi I have created PR for it. PR link: https://github.com/dvstechlabs/Noteslify/pull/201
Please review it and merge it.

**Comment by devarshishimpi** [comment]
Done
