### ISSUE TITLE
Encryption needed on Recycle Bin Page

### ISSUE THREAD

**Issue by devarshishimpi** [dvstechlabs/Noteslify#212]
On moving the items to recycle bin, they get shown in the encrypted format
and on restoring the note, it gets shown in its original format

@Gauravdarkslayer Here as well

**Comment by Gauravdarkslayer** [comment]
Sure will do this.

**Comment by devarshishimpi** [comment]
Great

**Comment by devarshishimpi** [comment]
Fixed

**Comment by devarshishimpi** [comment]
https://github.com/dvstechlabs/Noteslify/pull/219
