### ISSUE TITLE
🐛 [BUG] – lack full dark mode

### ISSUE THREAD

**Issue by Dun-sin** [dvstechlabs/Noteslify#227]
### Description

I don't know if this is intentional or not, and wasn't sure to create this issue as a bug or a feature.

But would be nice if the dark mode was throughout the app and not just the navigation bar

### Reproduction steps

```bash
1. Go to your dashboard
```

### Screenshots
![image](https://user-images.githubusercontent.com/78784850/200637401-cd2c58c2-ff74-4eac-b003-9908330bab4c.png)

### Browsers

Firefox

### OS

Windows

**Comment by devarshishimpi** [comment]
Yes, This is a work in process and will be applied throughout the app.

Please find the same issue number here https://github.com/dvstechlabs/Noteslify/issues/37

Currently, I plan to improve the landing page first and then perhaps a new notes UI dashboard as well.

**Comment by devarshishimpi** [comment]
I'll be closing this issue

**Comment by Dun-sin** [comment]
hi @devarshishimpi does the dark mode feature you are working on include an icon to easily identify what the toggle is for?

**Comment by devarshishimpi** [comment]
> hi @devarshishimpi does the dark mode feature you are working on include an icon to easily identify what the toggle is for?

The toggle will be replaced with dark/light theme-switching icons.
