### ISSUE TITLE
Refactoring toaster (Improper implementation of react-toastify)

### ISSUE THREAD

**Issue by RakibRahman** [dvstechlabs/Noteslify#233]
### What would you like to share?

Currently, the toaster component is implemented improperly. as 'react-toastify' is used to show toast messages, we only need to place/import  ```<ToastContainer/>``` component only on the main or root component such as App.js

But  ```<ToastContainer/>``` is imported manually in every component that uses toast functionality, which is unnecessary and repetitive. For example, check the Notes.js and Account.js component.

**Comment by devarshishimpi** [comment]
Definitely!

**Comment by RakibRahman** [comment]
@devarshishimpi sure! :)

**Comment by devarshishimpi** [comment]
Fixed
