### ISSUE TITLE
[Enhancement] Back-to-Top button alignment was not at right with form button

### ISSUE THREAD

**Issue by Manikanta528** [dvstechlabs/Noteslify#243]
### just need a little bit of alignment to the back-to-top button

<img width="526" alt="Screenshot 2022-11-16 at 9 01 18 PM" src="https://user-images.githubusercontent.com/62022514/202223295-84d754fb-7284-4d2a-bd6c-8b0c7511ce69.png">

**Comment by jainPrajwal** [comment]
Hey @Manikanta528 , can I take up this issue..?

**Comment by devarshishimpi** [comment]
@Manikanta528 @jainPrajwal This issue won't be worked on as we are shifting to a fresh new landing page built with Tailwind CSS. Check Out this issue https://github.com/dvstechlabs/Noteslify/issues/237
If you want to work on a back-to-top button on the new landing page, you can comment on the issue for the same.

Thanks again 😄
