### ISSUE TITLE
🐛 [BUG] - LocalStorage theme value not updated when switch to different theme

### ISSUE THREAD

**Issue by JunDevHarsh** [dvstechlabs/Noteslify#250]
### Description

When a user tries to switch the current theme for the first time, the localStorage doesn't update the `theme` value because the initial value of the `theme` is null.

### Reproduction URL

https://github.com/JunDevHarsh/Noteslify

### Reproduction steps

```bash
1. Go to 'apps/web/frontendnew'
2. Start to react app on 'localhost:3000'
3. Toggle the theme button
4. See localStorage theme value. If you switch to the dark theme then the theme value in localStorage will be null or light
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Windows

**Comment by devarshishimpi** [comment]
Hey, Thanks For Report the issue along with a PR for it!!

**Comment by devarshishimpi** [comment]
Fixed
