### ISSUE TITLE
🐛 [BUG] - Create multiple accounts using same email and username

### ISSUE THREAD

**Issue by devXprite** [dvstechlabs/Noteslify#257]
### Description

Users can create multiple accounts using the same email address as long as the case is different. For example, "user@gmail.com" and "USER@gmail.com" are treated as different emails. This is a problem creates confusion when trying to identify unique users.

The same issue exists with the username field. Users can create multiple accounts using the same username as long as the case is different.

It should treat email addresses and usernames as case-insensitive when creating new accounts. If an email or username has already been used to create an account, the website should prevent the creation of a new account using the same email or username with different case.

### Reproduction URL

https://noteslify.stonecss.com/

### Reproduction steps

```bash
1. Go to the website and click the "Get Started" button.
2. Enter "user@example.com" as the email and "USER" as the username.
3. Click the "Register" button.
4. Observe that a new account is created.
5. Repeat steps 2-4 using the same email and username with different case (e.g. "USeR@example.com" and "USeR").
6. Observe that another account is created.
```

### Browsers

Chrome

### OS

Linux

**Comment by devXprite** [comment]
I want to work on this issue

**Comment by devarshishimpi** [comment]
@devXprite Thanks For Your Findings! I have assigned you the issue!
