### ISSUE TITLE
🐛 [BUG] - <Decrypting in some systems causes error>

### ISSUE THREAD

**Issue by Gauravdarkslayer** [dvstechlabs/Noteslify#259]
### Description

Suggest a fix for below error causes while decrypting.
![image](https://user-images.githubusercontent.com/18503497/211168787-23146d0f-4b2f-4169-8257-b9a2be9e291b.png)

### Reproduction URL

https://github.com/dvstechlabs/Noteslify/tree/main/apps/web/backend/helper

### Reproduction steps

```bash
While retrieving the notes we will notice an error for `bad decrypt`.
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### OS

Windows

**Comment by devarshishimpi** [comment]
Fixed
