### ISSUE TITLE
Complete Noteslify Landing Page with all necessary components

### ISSUE THREAD

**Issue by devarshishimpi** [dvstechlabs/Noteslify#31]

**Comment by khushi818** [comment]
Please assign it to me

**Comment by CleverOscar** [comment]
Not sure if this issue is still being worked on or not, but if there's anything I can help with I'd like to jump on this task.

**Comment by devarshishimpi** [comment]
> Not sure if this issue is still being worked on or not, but if there's anything I can help with I'd like to jump on this task.

@khushi818 is working on the issue and should be fixed by the 25th of this month. Also, yes this is being worked on by making the landing page look better.

**Comment by devarshishimpi** [comment]
https://github.com/dvstechlabs/Noteslify/pull/39#

**Comment by devarshishimpi** [comment]
https://github.com/dvstechlabs/Noteslify/pull/48

**Comment by devarshishimpi** [comment]
Fixed
