### ISSUE TITLE
Replace Boxicons with Fontawesome CDN Icons

### ISSUE THREAD

**Issue by devarshishimpi** [dvstechlabs/Noteslify#32]

**Comment by Ravina-Deogadkar** [comment]
Can I take this issue?

**Comment by devarshishimpi** [comment]
> Can I take this issue?

@Ravina-Deogadkar Sure, I have assigned you as well.
Please do make sure you use this Kit URL
```<script src="https://kit.fontawesome.com/c2536b674d.js" crossorigin="anonymous"></script>```
Using the Latest v6.x

**Comment by devarshishimpi** [comment]
@Ravina-Deogadkar Is the issue still being worked on??? By when shall the PR be ready?

**Comment by Ravina-Deogadkar** [comment]
Yes I am working on it. I can see there is very limited icons available for free 
https://fontawesome.com/search?o=r&m=free&f=brands%2Csharp%2Cclassic

The lock symbol is not available

**Comment by devarshishimpi** [comment]
> Yes I am working on it. I can see there is very limited icons available for free https://fontawesome.com/search?o=r&m=free&f=brands%2Csharp%2Cclassic
> 
> The lock symbol is not available

Great, Are you referring to this? https://fontawesome.com/icons/lock?s=solid&f=classic

**Comment by devarshishimpi** [comment]
Fixed in https://github.com/dvstechlabs/Noteslify/pull/42
