### ISSUE TITLE
Add Markdown Support for Title And Description Of Notes

### ISSUE THREAD

**Issue by devarshishimpi** [dvstechlabs/Noteslify#36]
Add Markdown and Word Document Style Editing Of Notes

**Comment by Ravina-Deogadkar** [comment]
Can I take this issue If no one is working?

**Comment by devarshishimpi** [comment]
> Can I take this issue If no one is working?

Yes, Sure

**Comment by Ravina-Deogadkar** [comment]
I have only added markdown support for preview shall I add a markdown editor to add and edit?

[screencast-localhost_3000-2022.10.01-22_54_39.webm](https://user-images.githubusercontent.com/49125074/193448406-a2573103-19af-4f62-a6e6-487959b3e01d.webm)

**Comment by devarshishimpi** [comment]
> I have only added markdown support for preview shall I add a markdown editor to add and edit?
> 
>  screencast-localhost_3000-2022.10.01-22_54_39.webm

Yes sure.

**Comment by Ravina-Deogadkar** [comment]
But adding a markdown editor in the modal will break down the modal and it won't look good in small size (modal width).

https://codesandbox.io/s/markdown-editor-for-react-izdd6?file=/index.js:61-105

**Comment by devarshishimpi** [comment]
> But adding a markdown editor in the modal will break down the modal and it won't look good in small size (modal width).
> 
> https://codesandbox.io/s/markdown-editor-for-react-izdd6?file=/index.js:61-105

True. Can we just reduce the gap between the modal border and the internal description/title inputs? ( For width )
And, Remove the Title And Description Label and add it to the Input itself? ( For Height )

**Comment by Ravina-Deogadkar** [comment]
It's making modal unstable.

[screencast-localhost_3000-2022.10.02-19_41_38.webm](https://user-images.githubusercontent.com/49125074/193458603-aaa1bc6f-03c6-442f-989e-e455aa9fcd1a.webm)

**Comment by devarshishimpi** [comment]
Oh okay. So, make the PR without the markdown editing options, but markdown supported. Like you can use markdown like the previous screen recording you sent. Also, do keep it extended like the second screen recording just so that more space for notes typing.
