### ISSUE TITLE
Account Settings Control

### ISSUE THREAD

**Issue by devarshishimpi2** [dvstechlabs/Noteslify#38]
Add a Navbar Element called "My Account" which lets user control their account settings

**Comment by CleverOscar** [comment]
If no one has started this task, I'd like to take it on.

**Comment by CleverOscar** [comment]
If this task is still available I'd like to jump on it

**Comment by devarshishimpi** [comment]
> If this task is still available I'd like to jump on it

@CleverOscar Sure, I have assigned the issue to you.

**Comment by CleverOscar** [comment]
It's seems like I need some type of development api in order to access the user account when in development. Unless there is a way around this, I can't seem to start on this task.

I can't connect to the database due to a client api error

**Comment by devarshishimpi** [comment]
https://github.com/dvstechlabs/Noteslify/issues/40

**Comment by devarshishimpi** [comment]
> 

You can get started now. I have added the `.env` configuration required for the backend in the Readme. Sorry for the inconvenience that it wasn't present before. After which this will start running locally on your system where you can create dummy users.

**Comment by MrKrishnaAgarwal** [comment]
This issue was completed in #60 

Closing!!
