### ISSUE TITLE
Replace Unicons with Fontawesome CDN Icons

### ISSUE THREAD

**Issue by devarshishimpi** [dvstechlabs/Noteslify#43]
@Ravina-Deogadkar Could you handle this issue as well?

**Comment by devarshishimpi** [comment]
Or I'll take this issue.

**Comment by Ravina-Deogadkar** [comment]
Sure, I'll do that

**Comment by devarshishimpi** [comment]
> Sure, I'll do that

Oh Okay.

**Comment by devarshishimpi** [comment]
Fixed In https://github.com/dvstechlabs/Noteslify/pull/45
