### ISSUE TITLE
Notes Model PopUp on click

### ISSUE THREAD

**Issue by khushi818** [dvstechlabs/Noteslify#44]
![notes](https://user-images.githubusercontent.com/81404366/190902439-a532f52f-decc-4458-aba7-d1e76f8d77e8.PNG)

The model should pop up upon clicking the notes itself. We can only do this by clicking the three dots. This is a feature to be added.

**Comment by Ravina-Deogadkar** [comment]
Can I take this issue

**Comment by devarshishimpi** [comment]
> Can I take this issue

Sure.

**Comment by Ravina-Deogadkar** [comment]
Modal should open on clicking notes itself does this means removing edit from the three dots? And is it clicking anywhere on the note box or just the title?

**Comment by devarshishimpi** [comment]
> Modal should open on clicking notes itself does this means removing edit from the three dots? And is it clicking anywhere on the note box or just the title?

Modal Should open on clicking notes, Like a preview of the notes. Also yes, Clicking anywhere in the Notes Box.
The edit button is not to be removed. Basically clicking the note anywhere gives a preview ( Non-Editable ) and Clicking the Edit Button lets editing the notes as is now.

**Comment by khushi818** [comment]
> Modal should open on clicking notes itself does this means removing edit from the three dots? And is it clicking anywhere on the note box or just the title?

the three dotes **need not** to be removed.  You just need to add additional feature where you can click anywhere on the note so that you can see the description about it. I hope it clears your doubt.

**Comment by Ravina-Deogadkar** [comment]
Got it

**Comment by Ravina-Deogadkar** [comment]
[screencast-nimbus-capture-2022.09.24-20_30_56.webm](https://user-images.githubusercontent.com/49125074/192105743-2a1a3063-b705-4ece-a9b5-25f438f66c69.webm)

Is it correct?

**Comment by devarshishimpi** [comment]
> screencast-nimbus-capture-2022.09.24-20_30_56.webm 
> Is it correct?

Yes works, you can remove the Title and Description part from the preview so that the note content is shown more,

**Comment by devarshishimpi** [comment]
Fixed In https://github.com/dvstechlabs/Noteslify/pull/49

**Comment by khushi818** [comment]
@Ravina-Deogadkar  thank you for the awesome work :)
