### ISSUE TITLE
Add Issues Templates

### ISSUE THREAD

**Issue by devarshishimpi** [dvstechlabs/Noteslify#46]

**Comment by Mannuel25** [comment]
Hello @devarshishimpi , I'd Iove to take this up. Kindly assign it to me.

**Comment by ericspring08** [comment]
> @ericspring08 Could You Help with this? Also, another, https://github.com/devarshishimpi/Stone-CSS-Website/issues/42

Sure

**Comment by devarshishimpi** [comment]
> > @ericspring08 Could You Help with this? Also, another, [devarshishimpi/Stone-CSS-Website#42](https://github.com/devarshishimpi/Stone-CSS-Website/issues/42)
> 
> Sure

Thank You, I have assigned you the same.

**Comment by MrKrishnaAgarwal** [comment]
Hey,
I can work on this issue @devarshishimpi

**Comment by devarshishimpi** [comment]
> Hey, I can work on this issue @devarshishimpi

Hi Sure

**Comment by devarshishimpi** [comment]
@MrKrishnaAgarwal Could you complete this by today?

Issues include 
1. Bug Issues
2. Feature Request
3. Contact Support

**Comment by MrKrishnaAgarwal** [comment]
Hey, sorry but not by today
Will do it by tomorrow

**Comment by devarshishimpi** [comment]
> Hey, sorry but not by today Will do it by tomorrow

Sure

**Comment by devarshishimpi** [comment]
@MrKrishnaAgarwal Could you complete this today?

**Comment by MrKrishnaAgarwal** [comment]
> @MrKrishnaAgarwal Could you complete this today?

I'll do it asap today itself as soon as I reach home

**Comment by MrKrishnaAgarwal** [comment]
Hey, Yes
I got it @devarshishimpi

**Comment by devarshishimpi** [comment]
@MrKrishnaAgarwal Where's the progress reached?

**Comment by MrKrishnaAgarwal** [comment]
> @MrKrishnaAgarwal Where's the progress reached?

Its almost completed
Will make PR's soon
