### ISSUE TITLE
Make Search Functionality Working

### ISSUE THREAD

**Issue by devarshishimpi** [dvstechlabs/Noteslify#54]
Making the Search Button at Noteslify Dashboard working with MongoDB Atlas and MongoDB Search Feature.

**Comment by nmathew98** [comment]
Hi, could I be assigned to this issue? Thanks!

**Comment by devarshishimpi** [comment]
> Hi, could I be assigned to this issue? Thanks!

@nmathew98 Sure. and done.

**Comment by devarshishimpi** [comment]
@nmathew98 Where's the progress reached?

**Comment by nmathew98** [comment]
> @nmathew98 Where's the progress reached?

have not started on it yet, will push a PR for review by the weekend at the latest!

**Comment by nmathew98** [comment]
This issue is closed? Ws just going to start work on it today haha. It's alright if it is, will unassign myself

**Comment by devarshishimpi** [comment]
> This issue is closed? Was just going to start work on it today haha

Yes, got merged in the previous one. I have commented on your PR itself.
