### ISSUE TITLE
Change Title And Description Text Optimized For SEO

### ISSUE THREAD

**Issue by devarshishimpi** [dvstechlabs/Noteslify#57]
Changing the Default React App Text and Description and other related SEO fields.

**Comment by akhilsharmaa** [comment]
I would like to work on this.

**Comment by devarshishimpi** [comment]
> I would like to work on this.

Sure. @akhilsharmaa

**Comment by devarshishimpi** [comment]
@akhilsharmaa Where's the progress reached?

**Comment by akhilsharmaa** [comment]
Hey! Can you specify what specific changes we want, I am unable to get proper idea of what is to be done here?

**Comment by devarshishimpi** [comment]
Yes, we have to replace the current `Create React App` SEO Meta Tags and assets with the Respective Noteslify needed meta tags.
