### ISSUE TITLE
chore: Add Pull Request Template 

### ISSUE THREAD

**Issue by MrKrishnaAgarwal** [dvstechlabs/Noteslify#58]
Let's add PR Template to this repository

**Comment by MrKrishnaAgarwal** [comment]
I'll make a PR adding the changes soon :)

**Comment by MrKrishnaAgarwal** [comment]
@devarshishimpi Please Review The PR :)

**Comment by devarshishimpi** [comment]
> @devarshishimpi Please Review The PR :)

Yes, merged. But Don't add `good first issue` label just anywhere tho

**Comment by MrKrishnaAgarwal** [comment]
> 
> Yes, merged. But Don't add `good first issue` label just anywhere tho

Okay!

**Comment by devarshishimpi** [comment]
I don't think this issue has too many changes for Hacktoberfest.

**Comment by devarshishimpi** [comment]
But yes, this one is part of Hacktoberfest https://github.com/dvstechlabs/Noteslify/issues/46

**Comment by MrKrishnaAgarwal** [comment]
> But yes, this one is part of Hacktoberfest https://github.com/dvstechlabs/Noteslify/issues/46

That was made before Oct 1

**Comment by devarshishimpi** [comment]
> > But yes, this one is part of Hacktoberfest #46
> 
> That was made before Oct 1

The PRs made after Oct 1 is considered for Hacktoberfest even if the issue was made before the same.

**Comment by MrKrishnaAgarwal** [comment]
> > > But yes, this one is part of Hacktoberfest #46
> > 
> > That was made before Oct 1
> 
> The PRs made after Oct 1 is considered for Hacktoberfest even if the issue was made before the same.

See,
Even every small contributions are also counted in Hacktoberfest, it doesn't depend on big changes

My changes are ok

**Comment by MrKrishnaAgarwal** [comment]
@devarshishimpi You should definitely add and approve the PR, but it's fine
If you don't want to

**Comment by devarshishimpi** [comment]
> @devarshishimpi You should definitely add and approve the PR, but it's fine If you don't want to

I have approved the PR and merged it.

**Comment by devarshishimpi** [comment]
> > > > But yes, this one is part of Hacktoberfest #46
> > > 
> > > 
> > > That was made before Oct 1
> > 
> > 
> > The PRs made after Oct 1 is considered for Hacktoberfest even if the issue was made before the same.
> 
> See, Even every small contributions are also counted in Hacktoberfest, it doesn't depend on big changes
> 
> My changes are ok

Yes, but doesn't mean any sort of extremely small change. Also, as I said you may complete the issue https://github.com/dvstechlabs/Noteslify/issues/46 and get it approved for Hacktoberfest specifically.

**Comment by MrKrishnaAgarwal** [comment]
Okay
No problem 👌

**Comment by devarshishimpi** [comment]
This issue is also made part of Hacktoberfest.

**Comment by MrKrishnaAgarwal** [comment]
> This issue is also made part of Hacktoberfest.

Let's talk on discord please
