### ISSUE TITLE
Change Password Functionality

### ISSUE THREAD

**Issue by shivamchourasia4** [dvstechlabs/Noteslify#61]
Password change functionality can be added in accounts section.

**Comment by shivamchourasia4** [comment]
I would like to work on this. Can some assign this to me?

**Comment by devarshishimpi** [comment]
Sure.

**Comment by devarshishimpi** [comment]
Fixed

**Comment by devarshishimpi** [comment]
@shivamchourasia4 Could you look into this further? Password not changing and no response on clicking the Password Reset in the production version at https://noteslify.vercel.app

**Comment by shivamchourasia4** [comment]
Got it.Somehow, there is an extra "/" in the put request.

<img width="694" alt="Screenshot 2022-10-03 at 12 33 26 AM" src="https://user-images.githubusercontent.com/73788982/193471547-22231fab-bf1a-4d6c-a905-e9dd114bb054.png">

**Comment by devarshishimpi** [comment]
Yes, Found it.

**Comment by devarshishimpi** [comment]
![image](https://user-images.githubusercontent.com/43378923/193506769-32d672c6-aeef-49ca-87cf-704200c3ed48.png)

Looks Like it is present in the frontend.

**Comment by devarshishimpi** [comment]
![image](https://user-images.githubusercontent.com/43378923/193507334-e1706a6d-4aa2-407a-921e-58e97e99616a.png)
 Now 404

**Comment by devarshishimpi** [comment]
I have reverted the backend as of now.

**Comment by shivamchourasia4** [comment]
this is also working fine locally.

**Comment by devarshishimpi** [comment]
> this is also working fine locally.

Exactly. I think both these issues have common problems.

**Comment by devarshishimpi** [comment]
Issue fixed
