### ISSUE TITLE
Update and Add More Issue Templates

### ISSUE THREAD

**Issue by MrKrishnaAgarwal** [dvstechlabs/Noteslify#63]
I'll turn bug.md and feature_request.md to issue forms, and add more issue templates.

Should I work on this?

@devarshishimpi

**Comment by devarshishimpi** [comment]
> I'll turn bug.md and feature_request.md to issue forms, and add more issue templates.
> 
> Should I work on this?
> 
> @devarshishimpi

That's what we have to do in the other issue which is open. And yes, it's assigned to you.
