### ISSUE TITLE
Recycle Bin Stuck in Production Version.

### ISSUE THREAD

**Issue by devarshishimpi** [dvstechlabs/Noteslify#66]
I have attached a screenshot below. The loader looks stuck around 50%. Bin won't open in the production version.

![image](https://user-images.githubusercontent.com/43378923/193471111-811e10ec-daf8-47b6-879b-caf84cac0b03.png)

**Comment by shivamchourasia4** [comment]
Looking into it!

**Comment by shivamchourasia4** [comment]
It is giving 404 in production. Is the backend deployed properly?

**Comment by devarshishimpi** [comment]
Yes, both are deployed properly. Checked it again. Similar 404 issues like this one https://github.com/dvstechlabs/Noteslify/issues/61

**Comment by devarshishimpi** [comment]
![image](https://user-images.githubusercontent.com/43378923/193516057-cbff7bee-2ae8-41b7-9292-093abe1c9f8d.png)

**Comment by devarshishimpi** [comment]
Some Heroku Logs

**Comment by devarshishimpi** [comment]
I have reverted the backend as of now.

**Comment by shivamchourasia4** [comment]
I can't seem to find it out as locally it is working fine.

**Comment by devarshishimpi** [comment]
> I can't seem to find it out as locally it is working fine.

Yes, Locally it works fine. Production, above are the errors found on Heroku. Apart from that, even in production. Postman is able to send successful request. Not sure about the 404 errors.

**Comment by devarshishimpi** [comment]
I think you may try deploying both frontend and backend on the Cloud?? And, you'll find the errors which are to be looked into.

**Comment by nmathew98** [comment]
@devarshishimpi can I help with this?

**Comment by devarshishimpi** [comment]
> @devarshishimpi can I help with this?

Sure.

**Comment by devarshishimpi** [comment]
Issue Fixed
