### ISSUE TITLE
Visual Bug: Unwanted scrollbar in Newsletter Section

### ISSUE THREAD

**Issue by Malay-dev** [dvstechlabs/Noteslify#68]
**Describe the bug**
The scrollbar in the Newsletter section in the Home can be unappealing to the users, and it can work out without using one, so I think we can fix it by changing some CSS.
**To Reproduce**
1. Go to https://noteslify.vercel.app/
2. Scroll down to the "Subscribe to our newsletter" section
3. See the bug

**Expected behavior**
ScrollBar for that section is not required.

**Screenshots**
![image](https://user-images.githubusercontent.com/91375797/193569947-ac69ac5b-fb8a-4847-95d1-ad42aa3287d9.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 106.0.5249.9
 
Can I take up to solve this if it is a valid issue for hacktoberfest?

**Comment by devarshishimpi** [comment]
Thanks For Pointing Out :)) Yes, it's valid for hacktoberfest and I have assigned you.

**Comment by devarshishimpi** [comment]
Fixed
