### ISSUE TITLE
No custom 404 Error Page

### ISSUE THREAD

**Issue by neupanedipen** [dvstechlabs/Noteslify#77]
**Is your feature request related to a problem? Please describe.**
Whenever user enters a route that doesn't exist, there's no custom 404 Error page to be displayed to the users.  

**Describe the solution you'd like**
A custom 404 Error page can be created and added to the routes so that the users are notified that the route doesn't exist. 

**Describe alternatives you've considered**
No alternatives other than creating a custom 404 page.

**Comment by devarshishimpi** [comment]
@neupanedipen Thanks For Pointing Out!!

**Comment by neupanedipen** [comment]
You can assign this to me. I can work on this.

**Comment by devarshishimpi** [comment]
> You can assign this to me. I can work on this.

Sure

**Comment by devarshishimpi** [comment]
Fixed
