### ISSUE TITLE
Fix spacing on Landing page info section

### ISSUE THREAD

**Issue by BraydenTW** [dvstechlabs/Noteslify#87]
**Describe the bug**
Currently, the spacing between elements on desktop and mobile for the Info component on the landing page aren't very neat.

**To Reproduce**
1. Go to https://noteslify.vercel.app/
2. Scroll down towards the bottom

**Expected behavior**
To have a cleaner look, the elements should be properly spaced out.

**Screenshots**
![image](https://user-images.githubusercontent.com/47185402/194731117-22d1680e-0d89-4094-b667-37ec17001410.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave
 - Version 1.45.88

**Additional context**

**Comment by nmathew98** [comment]
@devarshishimpi can I work on this?

**Comment by devarshishimpi** [comment]
> @devarshishimpi can I work on this?

It looks fixed after a while it was created
