### ISSUE TITLE
Navbar is not interactive 

### ISSUE THREAD

**Issue by PritamSarbajna** [dvstechlabs/Noteslify#92]
When I'm hovering over the navbar it is not interacting like it'd be good if its color changes or something

I'd love to work on it if assigned.

**Comment by devarshishimpi** [comment]
Which navbar were you referring to? The side nav after login or the one on the landing page?

**Comment by PritamSarbajna** [comment]
> Which navbar were you referring to? The side nav after login or the one on the landing page?

Navbar of the landing page

**Comment by devarshishimpi** [comment]
> > Which navbar were you referring to? The side nav after login or the one on the landing page?
> 
> Navbar of the landing page

Yes, Sure. That does need enhancement. The one after login won't be changed and looks fine.

**Comment by PritamSarbajna** [comment]
@devarshishimpi Thanks for assigning me 🙌

**Comment by devarshishimpi** [comment]
Fixed
