### ISSUE TITLE
Wrong backend server

### ISSUE THREAD

**Issue by nmathew98** [dvstechlabs/Noteslify#93]
**Describe the bug**
Fetching data from API fails with the following error:

**To Reproduce**
1. Go to the all notes page

**Expected behavior**
The page should load data from the API

**Screenshots**
<img width="945" alt="image" src="https://user-images.githubusercontent.com/55116576/194750364-d6516fad-b9af-40d6-bf69-c03887700b98.png">

**Comment by nalin-programmer** [comment]
Assign me this task

**Comment by devarshishimpi** [comment]
> Assign me this task

Sure. This issue does need a faster fix since it's running in production.

**Comment by nmathew98** [comment]
This is not a CORS issue, its checking the wrong backend server sorry haha

**Comment by devarshishimpi** [comment]
![image](https://user-images.githubusercontent.com/43378923/194752367-6243f049-7893-49b9-bff0-9c83abe534f1.png)

@nmathew98 Only loads the title

**Comment by devarshishimpi** [comment]
It's just for the previous notes, the new notes work fine

**Comment by devarshishimpi** [comment]
Correction : Issue fixed
