### ISSUE TITLE
Not all footer links are working

### ISSUE THREAD

**Issue by ann0nip** [dvstechlabs/Noteslify#99]
**Describe the bug**
The different links on the footer should work as the nav bar.

**To Reproduce**
1. Go to 'Home Page'
2. Click on the differents Links on the footer
3. Some of them are not working, but it does if you use the top nav links

**Expected behavior**
It should work as the top nav links

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [Chrome]
 - Version [105.0.5195.125 ]

**Comment by devarshishimpi** [comment]
Thanks For Pointing Out!!! It was scheduled to be added with the pricing page, even tho technically the privacy page is going to be free of cost

**Comment by devarshishimpi** [comment]
Fixed
